(async function main() {
    try {
        init()
    } catch (error)  {
        console.log("###error", error)
    }
}())